### ISSUE TITLE
Have a pattern to select a method among a list of values 

### ISSUE THREAD

**Issue by jbrenaudin** [goaop/framework#113]
=> We would like : only this methods (create, get, update, delete) are matched
execution(public **\*Controller->(create|get|update|delete)(*) )

=> Actually, we have : 
execution(public **\*Controller->create(*) )
             || execution(public **\*Controller->get(*) )
             || execution(public **\*Controller->update(*) )
             || execution(public **\*Controller->delete(*) )

**Comment by lisachenko** [comment]
Hello, thank you for the report. I will have a look on weekends. Probably, this will require only minimal changes in the pointcut parser, but not sure...

However, can I recommend you to use an annotation marker (eg. _Loggable_) for your needs instead of hard-coded pointcuts. And then just add this marker where needed.

Additional way for readable pointcuts is to use @Pointcut annotation:

``` php
class SomeAspect
{
    /**
     * Pointcut for create
     *
     * @Pointcut("execution(public **\*Controller->create(*))")
     */
    protected function onCreate() {}

    /**
     * Logic here, refer to $this->onCreate
     *
     * @Before("$this->onCreate")
     */
    protected function beforeLogic(MethodInvocation $invocation) {}

}
```

**Comment by lisachenko** [comment]
Pointcut syntax was extended. To specify multiple values for method names, just separate them with "|" symbol, e.g. `execution(public Demo\Example\General->publicHello|protectedHello(*))`
