### ISSUE TITLE
Issue loading class by static function using "self"

### ISSUE THREAD

**Issue by eriknyk** [goaop/framework#130]
Hi, 
I found a issue doing the following:
I create a class:  Example.php

```
<?php
class Example
{
    public function hello($value='')
    {
        echo "hello $value" . PHP_EOL;
    }
    public static function load()
    {
        $me = new self();
        return $me;
    }
}
```

and I'm setting a LoggerAspect using:

```
@Before("execution(public Example->*(*))")
```

after setting my: Kernel\ApplicationAspectKernel::getInstance(),.. etc.
and execute 

```
$e = Example::load();
$e->hello("ERIK");
```

It doesn't works!!! :(

But if I change my static funcion load(), so:

```
public static function load()
{
    $me = new Example(); // <-- Changing from: new self() to: new Example()
    return $me;
}
```

It works :), But I'm thinking that it is a unexpected behavior,.. can you tell me, it is a bug, or a limitation please,..

Best Regards.

**Comment by lisachenko** [comment]
This issue is also limitation, not a bug, because AOP creates a reverse-proxy class by renaming original class and extending it, so if you want to receive normal instance, you should use Late Static Bindind, just replace `new self()` with `new static()`.

Duplicates https://github.com/lisachenko/go-aop-php/issues/94

**Comment by lisachenko** [comment]
It will be nice to add this issue to the documentation, so everyone will be able to notice it.
