### ISSUE TITLE
The pattern of function interception is confusing

### ISSUE THREAD

**Issue by hax** [goaop/framework#133]
First, as I understand, current "interceptFunctions" feature only intercept system functions. So we'd better change the name of the option to "interceptSystemFunctions" which make it clearer.

Second, current `execution(Namespace\*(*))` is very confusing (waste me several hours to get it), it actually means any system calls under the namespace. Should it be `within(Namespace) && execution(\*(*))`?

Third, I hope go! aop add the support of interception for user-defined function. Example: `@Before(function(My\test*))` (I found that 'function' token already in PointercutLexer :)
This feature is critical for us to migrate from PHP-AOP to go! aop.

Thank you.

**Comment by lisachenko** [comment]
Interception for user-defined functions can be very tricky, especially when function is defined in the specific namespace. It's possible, but will require monkey-patching for functions too and this can take a lot of time to process source files.
One more reason why it's not implemented is my vision for object-oriented framework. AOP is pretty cool with classes and aspects, so I want to implement more features in that way.

Why can't you put you functions into the class as static methods?

**Comment by lisachenko** [comment]
I know, that pattern syntax is not documented well, so any help with documentation is appreciated :)

**Comment by hax** [comment]
1. After reading the AspectJ doc, I realize that current implementation of interception of internal functions should be write as `within(namespace\*) && call(*(*))`!
2. I don't understand why interception for user-defined functions are tricky. I think it's very similar to interception for method. And I'm trying to implement it this weekend.
3. Yes I can use static methods instead of function, but it's hard to change all the old codes. And I think it's better to support interception for user-defined function in the framework. For example,  with that, `test::double` of AspectMock could also support mocking of functions.

**Comment by lisachenko** [comment]
1. There are differences with AspectJ. Initially, I started with methods, so decided that I will work only with methods, so `within` is pure method matcher. It won't match properties, or functions in the namespaces. But I agree that this can be done for future (I want to support `withincode` and some more matchers, this will also include rewriting of `within` filter)
2. Without namespaces - yes, it's easy. This will work when user functions are defined in the global namespace and are used in the namespaced source code. If functions are defined within namespace, then weaver should change original name of function, for example, to `user_func_AopProxied` and create a function proxy with original name `user_func` in the same namespace.
3. It's not recommended to enable interception of functions for AspectMock. We discussed this feature early with @davert and decided not to use it, because it will dramatically decrease the performance of application.

**Comment by hax** [comment]
I just did a rough implementation for user-defined functions, see https://github.com/hax/go-aop-php/tree/test-intercept-functions 
If you think it's a right direction, I would like to improve it and create some pull requests.

**Comment by lisachenko** [comment]
@hax, thanks for research and implementation :) your idea is correct and correlates with my vision described early (create a function proxy and replace the original one with it), but this should be polished with tests and performance optimizations.

If you want to contribute, I can suggest your to split this task into several independent PR.

First part: add a proxy generator for user functions (it would be better to extend FunctionProxy or to add an additional check for user/system functions in the `getJoinpointInvocationBody` method). Add a tests for user functions. This is general part without extra requirements, so can be merged easily.

Second part: add new grammar syntax with updated parse table for production use. Add a test for parsing new expression. Do not add new token `withincode` now or adjust logic for debugging pointcut parse table. This part can be merged easily too.

Third part: integration of checks into AdviceMatcher and WeavingTransformer. Weaving transformer shouldn't differentiate between user functions and namespace functions. Do not split `WeavingTransformer->processFunctions` method into several methods, instead put an additional logic into `AdviceMatcher->getFunctionAdvicesFromAdvisor()` method to add an advices for user-defined function with some specific prefix. Add a new method `WeavingTransformer->adjustOriginalFunction()` that will replace an original names of functions with regular expression and call this method from `WeavingTransformer->processFunctions` for `$functionAdvices[AspectContainer::USER_FUNCTION_PREFIX]`. At that moment FunctionProxy will create a single file with mocks for system functions and user-defined functions, that will be stored as included file.

**Comment by hax** [comment]
I'll try my best to follow your path. But there are some points which I think need some discussion.

First, I started this issue because using `execution(Namespace\*(*))` to intercept internal functions seems too confusing. To be consistent, it should match the execution point of user-defined functions under Namespace. Currently I use `function(Namespace\*)` to avoid conflict, but I really think `execution(Namespace\*(*))` should be used instead and it should not be used to capture internal functions in the same time.

To intercept internal functions, we should use `within(Namespace\*) && call(*(*))`. I realize that we do not have real `within` pointcut now, but we could temporarily hard code `within(Namespace\*) && call(*(*))` pattern in grammar.

And the reason of using `call` for internal functions is, we really have no way to capture execution point of the internal functions/class methods. Current implementation is based on namespace hack, but it still can not deal with the case like `execution(json_encode(*))` for `array_map('json_encode', array)`, so `call` is more appropriate.

**Comment by lisachenko** [comment]
Let's discuss the pointcuts.

I think that we can not use `call` syntax anywhere in the Go! framework because we aren't able to support interception of calls in PHP. Proxies are triggered only during the execution of method/function. You can have a read an article about [differences between `call` and `execution`](http://perfspy.blogspot.ru/2013/09/differences-between-aspectj-call-and.html). So you variant `within(Namespace\*) && call(*(*))` is not looking nice like current one `execution(Namespace\*(*))` as they both are confusing.

We can extend execution pointcut for functions and accept both system and user-defined functions in that namespace. E.g. take a list of user-defined functions from one file add a list of system functions to that namespace and then perform analysis of pointcuts. This means that pointcut `execution(Namespace\*(*))` will match all user-defined functions for that namespace and will also match system functions.

For the future, we can utilize `ReflectionFunction->isUserDefined()`, `ReflectionClass->isUserDefined()` and `ReflectionMethod->isUserDefined()` to create a 'user-defined' check like this: `execution(Namespace\*(*)) && userDefined()`

**Comment by lisachenko** [comment]
Closing this one issue as inactive. Feel free to reopen if needed.
