### ISSUE TITLE
 Catchable fatal error

### ISSUE THREAD

**Issue by mustela** [goaop/framework#139]
I coded an aspect to work with this class (well I just copied it from your examples :) )

```
namespace Maven\Front\Actions;

class AddToCartAction extends Action {

    public function __construct ( \Maven\Front\Step $step, \Maven\Core\Cart $cart, $data ) {
        parent::__construct( $step, $cart, $data );
    }

    /**
     * 
     * @return \Maven\Core\Message
     * @throws \Maven\Exceptions\InvalidObjectTypeException
     */
    public function execute () {
         ........
    }
}

```

But when it runs I get 

Catchable fatal error: Argument 2 passed to Maven\Front\Actions\AddToCartAction::__construct() must be an instance of Maven\Core\Cart, instance of Maven\Core\Cart__AopProxied given, called in ....

This is the aspect

```
/**
 * Monitor aspect
 */
class MonitorAspect implements Aspect
{

    /**
     * @param MethodInvocation $invocation Invocation
     * @Before("execution(public Maven\Core\Cart->*(*))")
     */
    public function beforeMethodExecution(MethodInvocation $invocation)
    {

        $obj = $invocation->getThis();
        echo 'Calling Before Interceptor for method: ',
             is_object($obj) ? get_class($obj) : $obj,
             $invocation->getMethod()->isStatic() ? '::' : '->',
             $invocation->getMethod()->getName(),
             '()',
             ' with arguments: ',
             json_encode($invocation->getArguments()),
             "<br>\n";

    }

}
```

Any clue?

**Comment by lisachenko** [comment]
This issue is related to https://github.com/lisachenko/go-aop-php/issues/94. Please, show me the code, where instance of `Maven\Core\Cart` is created. Due to the nature of AOP implementation it requires Late Static Binding enabled for class creation. Probably, you call `new self()` inside `Maven\Core\Cart` or some static method with `self::methodName()`?. To work with AOP, you should change this to `static` keyword: `new static()`, `static::methodName()`, etc... Alternative way: exclude factory methods from the pointcut.

**Comment by mustela** [comment]
Yes, you were right. I just changed the new self() for new static(), and it's working now. 

Thanks again!

**Comment by lisachenko** [comment]
@mustela Welcome!
