### ISSUE TITLE
Private methods access

### ISSUE THREAD

**Issue by mustela** [goaop/framework#140]
Is there any way to let the aspect access to private methods? I've tried using 

```
 @Before("execution(private Maven\Core\Cart->*(*))
```

But it doesn't seem to be supported, 

_Fatal error: Uncaught exception 'RuntimeException' with message 'Private modifier is not supported' in /Users/mustela/sites/little-hero/wp-content/plugins/debug/vendor/lisachenko/go-aop-php/src/Go/Aop/Pointcut/PointcutGrammar.php on line 227_

and also

```
 @Before("execution( Maven\Core\Cart->*(*))
```

But I'm getting an exception 
_Uncaught exception 'Dissect\Parser\Exception\UnexpectedTokenException' with message ' in /Users/mustela/sites/little-hero/wp-content/plugins/debug/vendor/lisachenko/go-aop-php/src/Go/Core/AbstractAspectLoaderExtension.php on line 114_

Thanks!!

**Comment by lisachenko** [comment]
@mustela framework is based on the proxy pattern, so it's impossible to override a private method with proxy implementation. BTW, all AOP frameworks don't recommend to intercept private methods, because they are implementation details and can be changed easily.
Go! AOP follows this way: there is no need in intercepting private methods. What is your case to intercept them?

**Comment by mustela** [comment]
Thanks @lisachenko for the answer, I just want to track all the methods I have on a class. I want to know how many times some of them are executed, but most of them are private.
