### ISSUE TITLE
Different approach proposal?

### ISSUE THREAD

**Issue by TheCelavi** [goaop/framework#156]
This ought to be in new issue, sorry:

---

I am thinking about different approach - overriding autoloading, code regeneration without using proxy pattern: https://github.com/schmittjoh/JMSAopBundle/issues/23

What do you think?

---

JMS seams to agree, I do not expect from you to "drop everything" and start to work with me on this :), but I would really appreciate your opinion...

It seams to me that re-generation of class and injection of class paths into autoloader is fast, neat and easy to debug solution...

**Comment by lisachenko** [comment]
Hello, Nikola!
I had the same thoughts early to inject the code directly into classes during the development of framework, but then I faced limitations and disadvantages of such approach and switched to the current one.

Here are some disadvantages:
1. Non-transparent debugging of aspects and advices (it's impossible to put a breakpoint into the advice body, because it's directly injected into many places)
2. Worse debugging for general classes (look at FLOW3 - we need to search for the cache file to put a breakpoint). Go! AOP has unique feature that allow you to put a breakpoint into the original class and will hit this breakpoint, no need to search for this proxy file in a cache.
3. Less readable source code - spaghetti from aspects, original classes and invocations.
4. it's impossible (or very hard) to implement an around advice, only general before/after.

Related to the #95 #94

I think, that the decorator pattern is the best implementation of AOP for interpreted languages, whereas your approach is better for compiled languages.

Can I wonder, why do you want to use a suggested approach?

**Comment by TheCelavi** [comment]
Oh, I have not seen that this is already proposed....

To be honest, I do believe that AOP MUST be part of the PHP core, or at least via extension. Everything done trough scripting it is stalling until proper solution is released.

I wasn't aware that this approach was proposed. 

Instead of getting into discussion about compilation approach - since you are much longer into PHP AOP than me, I have to ask: is there anything that can be done that could promote AOP into PHP core? Was there any feature request? Anything at all? Can we ask for it?

**Comment by lisachenko** [comment]
> is there anything that can be done that could promote AOP into PHP core? Was there any feature request? Anything at all? Can we ask for it?

From my point of view, AOP will never be in the core, only as an extension or framework. We have a `runkit` extension for runtime class manipulation and potentially, `php-aop`.

For the future version of PHP (PHP7 and up) there is a small chance that PHP core will provide a userland hooks for compiling the source code from AST to opcodes. With such hooks AOP can be much easier and native.

If you want to ask internals - you can try to ask them :) More realistic way to start using AOP is to ask from PHP devs to implement "open" classes, this will give an ability to change method in a class with a proxy-method in runtime (like in Python or Ruby).

**Comment by TheCelavi** [comment]
Runkit seams to me as regeneration of class in runtime, instead of some "caching" time, it is a same idea.

php-aop is best fit of AOP requirements, but community and number of maintainers of this project is so small...

I honestly can not believe that AOP can not achieve much more support. I am not C developer and I can not help them to resolve this 5.5 issue... damn!

....

**Comment by lisachenko** [comment]
> I honestly can not believe that AOP can not achieve much more support. I am not C developer and I can not help them to resolve this 5.5 issue... damn!

It's not so easy to implement this kind of logic in the core, because it performs a lot of weird things with PHP and can easily lead to segmentation fault or incompatibility with opcode cachers.
