### ISSUE TITLE
Only caching classes that are referenced in aspects?

### ISSUE THREAD

**Issue by danslo** [goaop/framework#206]
Hello,

I took your suggestion from [here](http://magento.stackexchange.com/a/39875/140) and implemented Go! AOP in Magento. You can view this module [here](https://github.com/danslo/Danslo_Aop).

There are a number of things I still need to clean up / implement, but overall it's working really well.

The only major downside I currently see is that since we are effectively replacing the original magento autoloader, all autoloaded files will be cached, regardless if they are being modified/generated by the Go! AOP framework.

I know there is the path whitelist, but preferably I want to solve this without requiring users to programmatically adding paths to this. 

Since I do require them to register aspects, is there an easy way to ask Go! AOP "here is a list of aspect classes, which classes/methods are they referencing"? In that case I could do my own whitelisting :)

If I am asking something stupid, definitely let me know.

**Comment by lisachenko** [comment]
Hello, Daniel!

I glad to see that you have a success with integration of frameworks, so my congratulations for that. Regarding your question about cached version of files for AOP, currently I can't find a reliable way to bypass cache generation, because framework is using this cache for achieving of high performance. No runtime checks for aspects, analysis of `__DIR__`, `__FILE__`, `require`, `include`, etc

`whitelist` option only affects weaving of aspects into the concrete file, but even if the file is blacklisted, it should be analysed for possible include/require constructions and modified to give a control back to the framework (kind of viral modification).

However, your last part of question looks very interesting for me. I have a special warmup command in the framework, that accepts a path to the aspect kernel and then it tries to warmup cache for all .php files, performing analysis of classes. This command-line tool can be extended for utility functions: 
- Return list of aspects
- Return list of all pointcuts optionally filtered by the specific aspect
- Return list of joinpoints matching given pointcut

Using this CLI tools, you will be able to generate a whitelist of files to transform. But I don't like this approach, because any aspect can be changed during active development and this should bring full rescan of files (yeah, nature of cross-cutting concerns). Framework handles this situation now pretty nice by checking date modification of files and aspects in the cache. If you restrict this behaviour with `whitelist` option - you will lost this mechanism.

I have another one option for zero-config of AOP when using composer - add all necessary information to the composer.json file (`extra` section). This will require an additional script handler, that can write this information directly to the PHP code, but no extra steps will be needed from developers to create kernel class and to pass additional options.

Let me know, if you find my thoughts useful for you, then I can implement something for 1.0.0 version.

**Comment by danslo** [comment]
Thanks for the extended answer. I think your command line tool has the right idea, but I would want to programmatically access it.

Basically, I would just add an additional check [here](https://github.com/danslo/Danslo_Aop/blob/master/code/Model/Autoloader.php#L34) to see if the class is actually supposed to need modifications. This information requires parsing of the aspects, but I can also cache that information, no big performance hit expected.

Just trying to prevent a (mostly unmodified) copy of hundreds of files to live in Go! AOP's cache directory.

**Comment by lisachenko** [comment]
> Just trying to prevent a (mostly unmodified) copy of hundreds of files to live in Go! AOP's cache directory.

Ok, I know about this. Maybe symlinks can be a solution? (not for Windows platform...). 

> I think your command line tool has the right idea, but I would want to programmatically access it.

I'll think about API for that on weekends.

**Comment by lisachenko** [comment]
Today I received two additional requests by email to create a cache only for affected files by AOP and don't create a full copy of content of `appDir`.

So I'll investigate the possible way to do this, assuming that modern applications load most files with composer. Direct `include`/`require` operations in the code become rare and typically used for configuration/settings.

**Comment by danslo** [comment]
Awesome. For my use-case it would be great if you were to expose some (static?) method that returns a list of classes that are referenced in a particular aspect. With that I can build my own (cached) whitelist of files that I pass down to Go! AOP.

Reasons for this:
- Magento 1.x does not use composer and as such I am currently emulating their homebrew autoloader to pass files down to Go! AOP manually (luckily this will be solved for Magento 2.x).
- I require developers to register aspects through Magento configuration, so it should be trivial to say something like "here are my aspects, what classes should my autoloader pass down to `FilterInjectorTransformer::rewrite`?".
- I already hooked Go! AOP into Magento's caching system so it should be really easy to cache that list of affected class names.

**Comment by lisachenko** [comment]
Finally, it's ready: #219 

Now only affected files will be in the cache, will be merged into 1.0-dev (master) soon.

**Comment by danslo** [comment]
Wow, that is great! Eagerly awaiting the merge and I will test that PR later. If there is anything, I will let it know in the other issue.

**Comment by lisachenko** [comment]
Moreover, now I'm working in background on CLI-tools and providing an API to query information about matching joinpoints for the specific pointcut.

**Comment by danslo** [comment]
@lisachenko I just got back to trying 1.x in my module, it works perfectly without needing any changes to my code and only affected files appear cached. Thanks again!

**Comment by lisachenko** [comment]
You are welcome ) hope, that this can be useful for Magento too
