### ISSUE TITLE
Generators result in fatal error

### ISSUE THREAD

**Issue by TiGR** [goaop/framework#207]
Let's say you have two classes in separate files:

``` php
<?php

class GeneratorTest extends GeneratorTestParent {}
```

``` php
<?php

class AOPTestParent {
    protected function generator()
    {
        yield 'foo';
    }
}
```

Then, it is being internally converted to:

``` php
<?php

class AOPTestParent {
    protected function generator()
    { if (($__am_res = __amock_before($this, __CLASS__, __FUNCTION__, array(), false)) !== __AM_CONTINUE__) return $__am_res; 
        yield 'foo';
    }
}
```

And any inclusion of AOPTest results in `PHP Fatal error:  Generators cannot return values using "return"`, since return was added to that method.

**Comment by lisachenko** [comment]
I think, that this issue is related to the AspectMock due to `return $__am_res;`. Go! AOP uses another approach for creating proxies for methods, so this should work.

I have tested this now, everything is OK:

```
Ttl is: 10
Take 1.452ms to call method Demo\Example\CacheableDemo:getReport
Result is: 
object(Generator)[54]

Take 0.030ms to call method Demo\Example\CacheableDemo:getReport
Result is: 
object(Generator)[54]
```

Code of the method was changed to the following:

``` php
    public function getReport($from)
    {
        // long calculation for 100ms
        usleep(0.1*1e6);

        yield 100;
    }
```

Please notice, that generator instance was cached correctly (id: 54) :)
