### ISSUE TITLE
Cache Warmup with Annotations

### ISSUE THREAD

**Issue by jg-development** [goaop/framework#222]
I generate the _proxies, _annotations over the vendor/bin/warmup script.
Everything looks fine, but the annotation reader kills me.

```
PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'The directory "/var/www/api/data/cache/aop/_annotations" is not writable. Both, the webserver and the console user need access. You can manage access rights for multiple users with "chmod +a". If your system does not support this, check out the acl package.' in /var/www/api/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/FileCacheReader.php:194
```

All _annotation files are generated with the script, this exception is not necessary.
Is it possible to use Annotations with the feature of a read-only cache dir?
Greetings Jan

**Comment by jg-development** [comment]
It seems that the cache warmup is not generating all annotations.
I have the following annotation from the demoexample:

```
<?php
/**
 * Go! AOP framework
 *
 * @copyright Copyright 2012, Lisachenko Alexander <lisachenko.it@gmail.com>
 *
 * This source file is subject to the license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Demo\Annotation;

use Doctrine\Common\Annotations\Annotation;

/**
 * @Annotation
 * @Target("METHOD")
 */
class Cacheable extends Annotation
{
    /**
     * Time to cache
     *
     * @var int
     */
    public $time = 0;
}
```

A "time" annotation need to be generated in the warmup.
The call from the demoaspect:

```
$invocation->getMethod()->getAnnotation('Demo\Annotation\Cacheable')->time
```

wants to generate the annotation file -> error

Greetings Jan

**Comment by lisachenko** [comment]
Thank you for reporting the issue!

I had a look into the source code of doctrine/annotation package and can confirm that this issue is present, however I'm not sure that doctrine/annotation library can work with read-only filesystems. I saw exactly the same error when tested my app on Google AppEngine, but decided to ignore it and prepared annotations cache by hand.

To fix this issue, a separate issue should be reported and discussed on doctrine/annotation project, otherwise it will be impossible to use a generated cache with read-only filesystem.

**Comment by lisachenko** [comment]
Please, could you tell me your version of framework and `doctrine/annotations` packet. Additionally, attach a trace for this exception. Thanks!

**Comment by jg-development** [comment]
Hi,
we are using the Version "v1.2.4". Maybe that helps. But there is another approach.
The "GoAspectContainer" creates the "FileCacheReader" in the constructor. With a DI (or config) it maybe possible to inject a BlackHoleContainer or a MemcacheReader, ReadOnlyReader.
Hope this helps.

Greetings Jan

**Comment by lisachenko** [comment]
Hi, @jg-development!

You can adjust definition of annotation reader in you own container. To do this, just create a class that extends `\Go\Core\GoAspectContainer` and then write a class name for your container in the `containerClass` option for kernel initialization.

In your container class, just reconfigure a definition of `aspect.annotation.reader` service:

``` php
        $this->share('aspect.annotation.reader', function (Container $container) {
            $options = $container->get('kernel.options');
            $reader  = new AnnotationReader();
            if (!empty($options['cacheDir'])) {
                $reader  = new FileCacheReader(
                    $reader,
                    $options['cacheDir'] . DIRECTORY_SEPARATOR . '_annotations' . DIRECTORY_SEPARATOR,
                    $options['debug']
                );
            }

            return $reader;
        });
```

Hope, this information can help you to avoid issues with read-only filesystem and doctrine restrictions.

**Comment by jg-development** [comment]
Hi,

I will try that and give some Feedback... thx in advance.
By the way.... the warmup in the master branch works like a charm, with 0.6.0 90% errors.
Causing a f***\* upped deployment, we can only use tags. Do u now, when a new tag is coming out
from the master branch?

Greetings Jan

**Comment by lisachenko** [comment]
Hi, @jg-development, sorry missed your comment somehow ) 

Indeed, master branch has significant changes in the logic of processing of files and rely heavily on autoloading, so instead of analyzing everything, framework only checks files that are whitelisted. Also several transformers are disabled (first one is transformer for `include`|`require` operators and others are using quick exit if aspects are not applied to the concrete file)

Prepared, `1.0.0-alpha.1` tag for you, thank you for participation.
