### ISSUE TITLE
Edit Argument Types?

### ISSUE THREAD

**Issue by derekrprice** [goaop/framework#266]
I had an idea to define a @SimpleDateTime annotation which would reflect on the method's parameter types and if it found any strings had been passed where DateTime was declared in the prototype, then it would attempt to convert the argument to a DateTime.  Unfortunately, when I tried this, I still got this error message from PHP, before my aspect could intercept and replace the arguments:

`PHP Catchable fatal error:  Argument 1 passed to AOP\Duration::getReport() must be an instance of DateTime, string given, called in /var/www/html/ssl/h2o/lib-tmp/datetime.php on line 8 and defined in /var/www/html/ssl/h2o/cache/_proxies/AOP/Duration.php on line 26`

Is there any way to avoid this error?  This would be very useful for avoiding boilerplate code since DateTime math in PHP involves a lot of converting back and forth between strings and DateTime objects.

**Comment by lisachenko** [comment]
Hello, I think that this is impossible now, because AOP engine supports only `execution` type of joinpoints and not `call` like in AspectJ/Spring frameworks. This means, that all hooks will be called during the execution of method and all arguments are already given to the method. You should go upper (to the class that will pass this arguments) to have an ability to do what your want.

But I think, that there is a place somewhere in your code when you know all the arguments and can look at method to invoke, here you can apply an advice to it.

**Comment by lisachenko** [comment]
Can't be implemented now, closing.

**Comment by lisachenko** [comment]
This should be possible now via #297, just replace the arguments for invocation as needed. For example, if parameter is string and has an annotation `SimpleDateTime`, then replace this argument with `DateTime` instance
