### ISSUE TITLE
MonitorAspects extends an empty interface "Aspect"

### ISSUE THREAD

**Issue by ghost** [goaop/framework#322]
This returns me back

`PHP Fatal error:  Interface 'Go\Aop\Aspect' not found in /Path/To/My/Project/Aspect/MonitorAspect.php on line 16`

I verified the interface it's extending and it's empty. Why extend an empty interface? I'm assuming the error comes from the extension of the interface.

Any tips? I'm not sure what I'm doing incorrectly.

Running PHP 7.1.1 if that has any incidence.

**Comment by lisachenko** [comment]
Hi!
Errors about classes/interfaces that could not be found are typical result when you configure `appDir` and `includePaths` to the top-level directory in your project and AOP engine tries to intercept own classes, because they matched your configs.

To fix that problem just exclude vendor directories from analysis and parsing using `excludePaths` option.

**Comment by lisachenko** [comment]
Was your issue resolved? What was the cause?
