### ISSUE TITLE
[Documentation][Known issue] Warn about serialization/reflection BC breaks of weaved classes

### ISSUE THREAD

**Issue by TheCelavi** [goaop/framework#336]
Due to Go! AOP engine, weaving of model/value objects is not BC safe, especially when it comes to serialization/deserialization and usage of reflections.

Introduction of pointcuts of classes that are being used for serialization/deserialization or analyzed in runtime with reflections in the middle of the project exploitation could lead to various issues - which is result of introduction of proxy classes and additional level of inheritance.

This can not be fixed - it is just how Go! AOP engine works. 

However, this must be documented, explained with examples in order to enable users to know about this, reasons behind it and possible workarounds.

**Comment by lisachenko** [comment]
Nice catch, I know about this fact.

Ideas for investigation: generate a warning in the weaver to prevent interception of methods or properties if there is `Serializable` interface or there are `__sleep()`/`__wakeup()` methods in this class.
Typically this issue doesn't affect source code often because AOP typically applied to the services and they do not require serialization.

One more idea is to handle serialization issues by AOP itself ) Just add more magic by intercepting `serialize()` function and adjust serialized content on-the-fly.

**Comment by TheCelavi** [comment]
I am not sure, since custom serialization, __sleep/__wakeup can have infinite variations of serialization logic, it is going to be hard to support.

We have stumbled upon this issue, we found a workaround to handle it without any problems. That is why I think that it should be documented only, just a heads up should be sufficient.

**Comment by TheCelavi** [comment]
I have wrote article on this subject: http://go-aop-php.readthedocs.io/en/dev/articles/limitations_and_known_issues/serialization-reflections-and-weaving.html

Will close this issue since content is kinda available - documentation will go into production soon.

**Comment by lisachenko** [comment]
👍
