### ISSUE TITLE
[Integration][AspectMock] Changes in framework causes AspectMock to fail

### ISSUE THREAD

**Issue by bhoehl** [goaop/framework#363]
@lisachenko 
The latest development of GoAop framework requires a cache directory always.
When using $kernel->loadFile() it is no longer possible to mock php classes that reside in a different folder than the appDir. GoAop does not create  a cachedResource for those, as the path and the cachedPath are the same. So, no mocking is possible, as the transformation of php code does no longer happen.

FileterInjectionTransformer.php line 107
$cachedResource = self::$cachePathManager->getCachePathForResource($resource);
$cachedResource equals $resource

SourceTransformingLoader.php line 100
$metadata = new StreamMetaData($this->stream, $this->data);
...
CachingTransformer.php line 71
function transform() 
if ($cacheUri === $originalUri) {
    return false;
}

That causes the loaded file not to be processed.
When moving the temporarily created files below the appDir folder specified when initing the application everything works fine, but that is no solution to me.
It ought to be possible to load and mock any file from any path as before, using $kernel->loadFile().

**Comment by lisachenko** [comment]
Hi, as you noticed, cache directory is always required now. 

It's by design, because we want code to be processed faster, so if there are no changes, why do we need to analyse source code several times in our local applications.

Unfortunately there is no way to intercept functions in arbitrary directories: you should configure appDir to be on top and then use `includePaths`/`excludePaths` options to filter what you need to analyse

**Comment by bhoehl** [comment]
@lisachenko 
The issue is, that we dynamically create code, that we want to mock.
That implies to have a temporary folder in our project folder, so that it can be analysed.
It would be nice, to have another way of doing this, too.

**Comment by lisachenko** [comment]
> That implies to have a temporary folder in our project folder, so that it can be analysed.
It would be nice, to have another way of doing this, too.

There is also solution to utilize virtual file system (`vfs://`) for that, maybe in AspectMock itself?

**Comment by lisachenko** [comment]
Looks like something went wrong with source transformers in new release, need to recheck why AspectMock fails on this.

**Comment by ghost** [comment]
Hello guys, any news on this? 
I had to downgrade to `"goaop/framework": "2.1.1"`

**Comment by lisachenko** [comment]
@pierrefaure sorry, still haven't time to check this issue

**Comment by lisachenko** [comment]
Looks like the reason is an old format of transformer which doesn't return status of transformation.
See  https://github.com/goaop/framework/compare/2.1.0...2.2.0#diff-f386e6b5ef522b358ae07b56c73011b8 changes.

Need to mark all transformer as private and lock them for 3.0 to prevent errors in outside projects like AspectMock. All AspectMock logic could be implemented via general aspect and work for any classes, including mocking of final methods, etc.

**Comment by lisachenko** [comment]
Investigation of @ramsey UUID library issues:

https://github.com/ramsey/uuid/commit/734eb5638368463de88e4e33b8a5d6f8432fb490 - It's ok, new version of framework requires new version of PHP
https://github.com/ramsey/uuid/commit/bd7f7f3135b1cd751b8be06b66a721e13f3d5b06 - AspectMock related, need more information.
https://github.com/ramsey/uuid/commit/0068b1be550e3545ffe7d2e6f0d6e0de7ebe5643 - also ok, because of PHP5.4 support, which is not supported in new version of framework
https://github.com/ramsey/uuid/commit/dfd89e22750d23151c34e4dcc733c35083c2ecc8 - ramsey/uuid library requires AspectMock for mocking system functions.

So, only changes that affected `ramsey/uuid` library was in 2.2.0 version, because of changes in `cacheDir` semantic and changes in the transformers internal API.

Patch version of GoAOP should fix following:
 - [ ] Enable void return value for transformer, add deprecation notice for 2.x branch that transformers are internal part of framework. Moreover, 3.0 will have `string` return type, thus will break compatibility anyway, but `AspectMock` will work with this changes.
 - [ ] Allow empty `cacheDir` option for 2.x or make it default to some internal /tmp directory.

**Comment by rantonmattei** [comment]
Any news on this? Can we safely upgrade to `2.2.x`

**Comment by lisachenko** [comment]
I think it would be better to check manually. AFAIK, @DavertMik previously released version of AspectMock with updated dependency.

Sorry, for the inconvenience with `AspectMock`, i'm trying not to introduce breaking changes in it, but sometimes bugs can occur, it's just source code )

**Comment by lisachenko** [comment]
Closed by inactivity.
