### ISSUE TITLE
[Feature] Enable usage of parameter type widening for proxies

### ISSUE THREAD

**Issue by lisachenko** [goaop/framework#380]
Framework engine could use PHP7.2 feature for parameter type widening in generated proxies. This feature is described here: https://wiki.php.net/rfc/parameter-no-type-variance

When feature is enabled, then we can weak arguments for original methods and implement different advices that will be able to handle such arguments like `ParamConverter` from the Symfony.

Possible usage: automatic injection of value for tests, handling custom proxies, etc...

**Comment by TheCelavi** [comment]
Since we are using inheritance, we are unable to remove parameters from method signature - I am for that option (unfortunately, it is impossible to do it like in example below):

```php

class A_AopProxied 
{
    public method foo(ParamType $value, ParamOtherType $value2...) 
    {
    }
}

class A extends A_AopProxied 
{
    public method foo()
    {
           // invoke parent method with func_get_args
    }
}
```

Generating proxy methods in such way would allow us to use GoAOP for implementing adapter pattern, useful with vendor libraries....

However, this:

```php
class A extends A_AopProxied 
{
    public method foo($value, $value2...)
    {
           // invoke parent method with func_get_args
    }
}
```

is next best thing. So, yeah - this will be useful and powerful tool as well.
