### ISSUE TITLE
[Question] Avoiding return type conflicts when intercepting

### ISSUE THREAD

**Issue by reinfi** [goaop/framework#382]
I am intercepting a method to check required permissions. 

```php
/**
 * @AdminOrRight("ADMINISTRATE_EMPLOYEE")
 * @return ViewModel
 */
public function indexAction(): ViewModel
{
    return $this->createViewModel('path/to/template');
}
```

My Aspect looks like the following:

```php
     /**
     * @param MethodInvocation $invocation
     *
     * @return mixed
     * @Around("@execution(AdminOrRight)")
     */
    public function checkPermission(MethodInvocation $invocation)
    {
        if (!$this->isAdmin()) {
            $adminOrRight = $invocation->getMethod()->getAnnotation(AdminOrRightAnnotation::class);

            if (!$this->hasRight($adminOrRight->value)) {
                $object = $invocation->getThis();
                return $object->redirect()->toRoute(Route::UNAUTHORIZED);
            }
        }

        return $invocation->proceed();
    }
```

Following Code `return $object->redirect()->toRoute(Route::UNAUTHORIZED);`returns a response which is not of type `ViewModel` and that causes a fatal error because method indexAction allows only `ViewModel`.

I tried @Before but that does not stop the original method from being invoked.
Is there any chance to avoid the fatal error or do I need to remove the PHP 7 Return Types?

**Comment by TheCelavi** [comment]
You are using proper advice type.

Since your return type is typehinted with `ViewModel`, aspect must return instance of `ViewModel`.

I would not recommend to remove return typehint. Much better approach is to throw exception, something like `AccessDeniedException` (you are using Zend, right?)

On your application, you can have a global exception handler which catches all unhandled exceptions, that can process exception and if exception is instance of `AccessDeniedException` it will display custom error page (or do your redirection to `$object->redirect()->toRoute(Route::UNAUTHORIZED);`).

I do not know how is this handled in Zend, but Symfony provides this concept out-of-the-box.

**Comment by reinfi** [comment]
ok thanks. Then I'll go with the exception and handle it somewhere else.
