### ISSUE TITLE
[Support] Accessing private constants via static keyword results in fatal

### ISSUE THREAD

**Issue by reinfi** [goaop/framework#384]
Hey,

not sure if this is a known issue, found nothing about it.
We had the following issue:

```php
class x {
   private const A = 'B';

   /**
     * @OurAspect()
     */ 
   public function action()
   {
        return new ViewModel(static::A);
   }
```

This gives a fatal error, because the `private const A` is not reflected to the proxy class.
At the moment we could help ourself by making the constant protected.
Any idea if it could be solved or is this something aop can not handle?

**Comment by lisachenko** [comment]
Hi, you definitely have an error in your code, because when `static` keyword is used, it will be resolved via Late Static Binding to the child class (if present). In your case, it will be correct to use `self::A` instead.

You should always refer to private methods, properties and constants via `self` keyword.

**Comment by lisachenko** [comment]
Just for example, create class `B` that extends the class `A` and call it’s `action` method. You will get the same error :)

**Comment by reinfi** [comment]
> You should always refer to private methods, properties and constants via self keyword.

totally forgot the late static binding :-( 

Good and fast help als always :-)

**Comment by lisachenko** [comment]
You are welcome!

**Comment by func0der** [comment]
This problem still occures if you use `self` instead of `static`. 
I'll try to reproduce this and make a new issue.
The currenct behavior produces  `OriginName\Space\OriginClass::PRIVATE_PROPERTY_NAME` instead of `self::PRIVATE_PROPERTY_NAME` in the proxy class, if you want to start to investiage this ;)
