### ISSUE TITLE
Unable to use JMSSerializer with weaved classes

### ISSUE THREAD

**Issue by Rastusik** [goaop/framework#385]
The Serializer cannot access class properties, since the class autoloading is overriden with autogenerated proxies by AOP which extend the transformed original classes

**Comment by TheCelavi** [comment]
Unfortunately, there is no much that we can do, since it is known limitation of the framework, please see: http://go-aop-php.readthedocs.io/en/dev/articles/limitations_and_known_issues/serialization-reflections-and-weaving.html

And this is not an issue solely limited to Go! AOP, it is in fact a general limitation to any library that uses some kind of class proxying, see: https://github.com/schmittjoh/JMSSerializerBundle/issues/405

In general, I believe that we can not help you much. Article which I have pointed out to you already contains some of the strategies to tackle issue. And you can use idea from https://github.com/hauptsacheNet/metadata/commit/c4fc861781ff849d115d03ed6e8253c170425f45 to replace `\Metadata\ ClassMetadata`, either via Composer autoloading or you can intercept it via GoAOP and initialization interception.

I am going to close this issue. However, if you have any additional info, feel free to reopen it. If you find some other method and/or idea for workaround this limitation - please share. 

Thank you.

**Comment by Rastusik** [comment]
@TheCelavi thanks for the feedback! Actually I wanted to close the issue myself, because I found out, that the serialization actually works, altough not perfect. The use cases where it didn't work at all occured by my mistake. So just FYI, it is possible to serialize weaved objects using JMS serializer, but the mapping needs to be outside the serialized objects and the variable `$__joinPoints` should be excluded. As a solution I will propose to fix this in JMS serializer (https://github.com/schmittjoh/serializer/issues/854)

**Comment by lisachenko** [comment]
@Rastusik could you provide please serialized form of woven class? I have a guess, that your class should use protected or public properties, otherwise unserialization could fail for private properties.

I'm not sure will it be possible somewhen to have 100% working solution for intercepted properties or not, because we have inheritance rules and class internal structure both that have some restrictions.

**Comment by lisachenko** [comment]
@Rastusik it's also interesting, why `$__joinPoints` is present for serialization. It' s declared as static and shouldn't appear in serialized view. But `$__properties` could be present, yes.

**Comment by Rastusik** [comment]
@lisachenko it doesn't matter whetter a property is public, private, protected and even static, that's how JMS Serializer works. Nevermind, I think this should not be the responsibility of GoAOP, but of the Serializer, that's why I opened the issue there
