### ISSUE TITLE
How to dynamically listen for method calls?

### ISSUE THREAD

**Issue by imanghafoori1** [goaop/framework#400]
Currently, I am working on a laravel package:
https://github.com/imanghafoori1/laravel-HeyMan/

I need to use goaop package to register listeners (callbacks) when a method is called to authorize or authenticate.
But that should happen at runtime, I think there is no way to use annotations.
instead of : `@Before("execution(public Example->*(*))")`
I want to write a php code. (To tie the aspect into method invocation.)

Is there any straightforward way?

**Comment by lisachenko** [comment]
Hi, @imanghafoori1 If you don't like annotations and prefer to use code, then look at the `PointcutBuilder` class. It provides an API for manual registration of pointcuts, typically first string parameter is pointcut expression and second one should be closure that will be called.

Also, deep in the engine there is a feature, called dynamic interceptor, that decides in runtime should concrete joinpoint be matched or not. For example, look at the `MagicMethodPointcut` class that intercepts access to magic methods in a class. All these dynamic pointcuts are handled by `DynamicInvocationMatcherInterceptor` class.
So, you can craft your own interceptors, combine them with advisors and register via `registerPointcut()`, registerAdvisor()` calls instead of registering aspects.

Is it what you need?

**Comment by lisachenko** [comment]
Also, looking at your codebase, I want to mention Design-By-Contract paradigm, you could also have a look at [php-deal/framework](https://github.com/php-deal/framework). If combine it with Cucumber, then each docblock for the method can be the rule that will be verified automatically by the engine in runtime.

**Comment by imanghafoori1** [comment]
I think it should do the job hopefully,
by the way, is the php-deal framework is inspired by the concepts of eiffel language?

**Comment by lisachenko** [comment]
> by the way, is the php-deal framework is inspired by the concepts of eiffel language?

partially, yes )

**Comment by imanghafoori1** [comment]
Very nice and mind-blowing.

**Comment by lisachenko** [comment]
Ping, do you need some additional information? Or this issue can be closed?

**Comment by imanghafoori1** [comment]
I will reopen it, if needed.
Thank you for help
