### ISSUE TITLE
Framework performance metrics

### ISSUE THREAD

**Issue by nekulin** [goaop/framework#46]
how fast is your framework ?

**Comment by lisachenko** [comment]
Some numbers:
Page load-time for empty ZF2-application: 140ms
-//- with APC: 60ms
Page load-time for empty ZF2-application with **each** public/protected method is intercepted: 1000ms
-//- with APC: 500ms

It's the worst case. In a real application you typically use AOP in specific services, so overhead will be smaller. So having AOP+APC for 100ms - it's enough.

Each part of this library was designed for faster speed, hope, you like it )

**Comment by lisachenko** [comment]
To test performance on poor VPS, please compare backend time on demo site:
http://zf2.aopphp.com/?aspect vs http://zf2.aopphp.com

It's an empty ZF2 application that switches AOP on/off. It's the worst case of using AOP in application, because all public and protected methods are intercepted. Real application only apply aspects to several methods and classes, so overhead will be much smaller (20-30ms for bootstrap the AOP core and some amount of time to call an advice)
